module.exports = {
  TWITTER_CONSUMER_KEY: process.env.TWITTER_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET: process.env.TWITTER_CONSUMER_SECRET,
  COOKIE_KEY: process.env.COOKIE_KEY,
  MONGO_URI: process.env.MONGO_URI,
};
